### ISSUE TITLE
Nyla crashes during startup

### ISSUE THREAD

**Issue by pat-s** [nylas-mail-lives/nylas-mail#114]
Hi guys,

new to Nyla - just installed your fork via AUR (I'm on Arch).

Nyla crashes during startup - I see it popping up for 2 secs and it closes again.

nodejs 8.6.0
npm 5.4.2

any logs that would be helpful for you?

**Comment by seesemichaelj** [comment]
Not sure why you're dropping the s in Nylas lol.

I guess your nodejs and npm versions don't matter because you're not building from source correct?

Can you send us the AUR link you're using? Some other members (not NML main contributors) put together the AUR.

Running Nylas from command line and piping the stdout and stderr streams to a file would be helpful.

**Comment by seesemichaelj** [comment]
theres also log files in /tmp i believe that could help
