### ISSUE TITLE
"Nylas Mail is offline" error despite being connected

### ISSUE THREAD

**Issue by l2dy** [nylas-mail-lives/nylas-mail#169]
Fresh install of `nylas-mail-2.2.2.dmg`.

The offline notification won't go away even though emails were successfully retrieved (via IMAP, custom provider):

![offline](https://user-images.githubusercontent.com/14329097/32757309-cfd1adf0-c8d6-11e7-925b-0eaa31f87ad0.png)

@seesemichaelj edit: The below is a duplicate of #159 and is **not** to be considered as part of the issue. I'm keeping it for historical purposes
and when I attempt to snooze an email:

![screen shot](https://user-images.githubusercontent.com/14329097/32757270-9290311e-c8d6-11e7-8618-5689e376274f.png)

**Comment by l2dy** [comment]
The offline notification seems to be caused by using IPv6-only networks. After switching to a IPv4-capable network, it disappeared. The snooze bug however persisted.

**Comment by seesemichaelj** [comment]
First, thanks for providing feedback/bug reports! It's difficult for us to test everything so it's awesome that the community is actively running the app and producing bug reports.

Second, please write an issue per bug so that we can stay organized; I can understand if you thought these two issues may be related and I'll give you the benefit of the doubt :+1:. Given your last comment, I'm fairly certain they're separate issues. 

In fact a quick search provides your snooze issue is known and being discussed: #159 

I have modified this issue to reflect the above. I'm guessing we're pinging some IPv4 address to see if we have network access; probably a super simple fix!

**Comment by l2dy** [comment]
Yes, I indeed thought they were related. Thanks for pointing out #159 and modifying this issue, I tried to [search for `feature_usage`](https://github.com/nylas-mail-lives/nylas-mail/search?utf8=%E2%9C%93&q=feature_usage&type=Issues) but didn't find an existing issue. If the error message was included as text in that issue I would have found it and wouldn't report a duplicate bug.

**Comment by seesemichaelj** [comment]
fair enough! fixed the title/description of #159 to be easily discoverable :beers:

**Comment by dweremeichik** [comment]
It looks like we use the `is-online` npm module in the following file: https://github.com/nylas-mail-lives/nylas-mail/blob/18545f3add6cefe2af36ae80f5dd427bb1752ad2/packages/client-app/src/flux/stores/online-status-store.es6#L1 this is what is responsible for determining if the app is online.

**Comment by seesemichaelj** [comment]
looks like there is an option for ipv6: https://github.com/sindresorhus/is-online

**Comment by dweremeichik** [comment]
Yup, defaults to ipv4, which is the problem.

**Comment by dweremeichik** [comment]
I am now confused, according to this closed issue, it should fall back automatically. https://github.com/sindresorhus/is-online/issues/15

**Comment by l2dy** [comment]
[browser.js](https://github.com/sindresorhus/is-online/blob/master/browser.js#L12) uses [public-ip](https://github.com/sindresorhus/public-ip#usage) which doesn't fall back.

**Comment by seesemichaelj** [comment]
of course, ben was here already: 
![image](https://user-images.githubusercontent.com/549323/32819795-296a4e2c-c999-11e7-8eb5-c26ae4fbac14.png)

he is everywhere!

**Comment by seesemichaelj** [comment]
did some digging on https://github.com/sindresorhus/is-online/issues/15 and it looks like it doesn't fallback, but rather just provide the option of using IPv6, at the devs discrepancy. we'll see if they're willing for a PR/update on their end, otherwise we'll just do a fix on our end to do IPv6 if IPv4 fails

**Comment by l2dy** [comment]
In some corporate or public WiFi networks, DNS traffic to external servers could be blocked. Since this offline notification is rather prominent and keeps retrying, can we add an option to disable this check?
