### ISSUE TITLE
Update Electron to 1.7.11

### ISSUE THREAD

**Issue by AluminiumTech** [nylas-mail-lives/nylas-mail#199]
Hi,
I'd like to suggest updating the dependencies of this project including updating to Electron 1.7.11 (1.4.15 is the version used in Nylas Mail 2.2.2). This would require an upgrade to NodeJS 7.9.0 . 

I think this would be a good idea because it moves this project from Chromium 53 to Chromium 58 and thus brings about a ton of improvements in efficiency and performance.

**Comment by seesemichaelj** [comment]
The most difficult thing here is making sure that whoever does the upgrade **makes sure** that **all three** OS's (Windows, Mac, Linux) can compile with the updated NodeJS version. Don't only make sure they compile, but htey run and can do basic functionality (sending email, etc).

I **highly recommend** that the developer starts with a clean slate (deleting `node_modules` or even better, recloning your repo) during finally they build to make sure they aren't getting any bleeding effects from prior builds.

Do what you want (since I'm Mailspring now), but I hope you heed my warnings :)

**Comment by l2dy** [comment]
Fixed in be4d3be3a8f58ce61185566fb35c37ab172a56ba?

**Comment by seesemichaelj** [comment]
Woops, yup!
