### ISSUE TITLE
Email Forwarding loses all body text upon sending

### ISSUE THREAD

**Issue by tsikerdekis** [nylas-mail-lives/nylas-mail#38]
Any message forwarded loses its body content upon hitting send. Only the forwarded email content is retained but not any new text that is typed.

The error occurs on the master.

The following log relates to this issue but I am not sure if it is informative at all.

`[17362:0711/140120:INFO:CONSOLE(46)] "%c<tsikerm@wwu.edu> %c🔃 ✉️ (Sent Items) "Fwd: test1" - Tue Jul 11 2017 14:01:13 GMT-0700 (PDT)", source: /home/micdhack/Desktop/NotBacked/nylas-mail/packages/client-sync/src/shared/logger.es6 (46)
[17362:0711/140121:INFO:CONSOLE(31)] "Got error while trying to parse body path, assuming we need to migrate", source: /home/micdhack/Desktop/NotBacked/nylas-mail/packages/isomorphic-core/src/message-body-utils.es6 (31)
[17362:0711/140121:INFO:CONSOLE(31)] "Got error while trying to parse body path, assuming we need to migrate", source: /home/micdhack/Desktop/NotBacked/nylas-mail/packages/isomorphic-core/src/message-body-utils.es6 (31)
[17362:0711/140121:INFO:CONSOLE(46)] "%c<tsikerm@wwu.edu> %c🔚 📂 🆕  Sent Items done", source: /home/micdhack/Desktop/NotBacked/nylas-mail/packages/client-sync/src/shared/logger.es6 (46)
`

**Comment by dweremeichik** [comment]
Is this issue occuring in our fork only?

**Comment by agurz** [comment]
The log references this piece of code:

https://github.com/nylas-mail-lives/nylas-mail/blob/master/packages/isomorphic-core/src/message-body-utils.es6#L31

```
if (remainingId) {
    while (pathGroups.length < MAX_PATH_DIRS) {
        pathGroups.push(remainingId.substring(0, 2));
        remainingId = remainingId.substring(2);
    }
}
```

I think this error could be solved checking if `remainingId` is not `undefined` in the `while` condition. If it's checked outside, `remainingId` will eventually become `undefined` and the line `pathGroups.push(remainingId.substring(0, 2));` will throw an exception.

@dweremeichik, I can make a PR if you want

**Comment by dweremeichik** [comment]
That warning is thrown from (`tryReadBody`)  the function above the one you highlited. (On my mobile) unless I missed something that function does not call `pathForBodyFile`.

**Comment by agurz** [comment]
You're right, the problem is in `tryReadBody`. As far as I could see it's happening with emails sent from the client-app. If I send an email from outside (let's say gmail, for example) the email is received and the body is parsed ok. I'm still debugging, let you know if I find something

**Comment by agurz** [comment]
The error seems to be the client-app creating the file to save the email body when we create a new message, but not updating it at all. The file doesn't get updated because the `writeBody` function is called with `forceWrite = false` every time. I think we can change it to set `forceWrite = true` whenever the message is a draft. In one picture, what I propose is this change:

<img width="982" alt="screen shot 2017-07-14 at 11 52 02 pm" src="https://user-images.githubusercontent.com/13837769/28235935-77048568-68ef-11e7-9acf-352905fee09f.png">

As far as I tested it solves the problem and doesn't have a negative impact on performance because the file is written just 2 times (vs 1 before the change): one when we click on 'New message' and the other when we send it.

@dweremeichik if it's ok for you I can make a PR

**Comment by dweremeichik** [comment]
@agurz PRs are absolutely welcome! Once you submit one, we will likely get more eyes on it.

**Comment by dweremeichik** [comment]
So I see why it is not updating, like you stated. I suppose I would need to debug it myself to understand exactly why that function was designed that way, they have comments saying that it is slow to write to the file system, and if they can't write to the file system, they fall back to the DB. What bugs me is they aren't diffing the files at all, it's simply a test of whether the file exists or not. Perhaps their intent is to save interaction with the filesystem. Which means that they would always need to know before hand when they needed to update the file, hence the force write as you suggested. Sorry for the rant, verbalizing my thoughts...   Based on what I see, you are doing the right thing @agurz.

**Comment by seesemichaelj** [comment]
putting this here for future reference. in the new code drop from nylas, https://github.com/nylas/nylas-mail/commit/af3de338267fd7fedb4b2e263adc58a54d5b1374 removes forceWrite altogether. i'm keeping nylas' change (removing it) instead of our change (changing it) for the code dump merge. if this isn't right, we'll need to open another issue
