### ISSUE TITLE
CLA

### ISSUE THREAD

**Issue by step21** [nylas-mail-lives/nylas-mail#43]
Do the new maintainers want to continue to require a contributor license agreement? If they do, it would have to change from the one Nylas used and it would be less useful anyway, unless Nylas transfers their rights derived from the CLAs to the new maintainer(s) or some institution.
If they don't, the relevant documentation should be removed.

**Comment by tsikerdekis** [comment]
I am not sure if the CLA is even required for contributing to this repository. But if it were to be ever merged with nylas's then maybe it would be required?

**Comment by seesemichaelj** [comment]
It is not required for contributing to this repository since we do not even have a legal entity which would own such IP. If we ever merged with the official repo; we'd only be able to merge commits from people who signed the CLA (with Nylas' current standing on IP ownership, which may or may not change in the future).

**Comment by step21** [comment]
Ok, thanks for clarifying. Maybe then I'll make PR to remove references to it from this repo if I still find any, if that is ok.
Just FYI I think you would not need a legal entity, a person could be entrusted as well.
