### ISSUE TITLE
Version maintained by original author of Nylas Mail

### ISSUE THREAD

**Issue by franzos** [nylas-mail-lives/nylas-mail#52]
One of the previous Nylas Mail developers is already working on a fork. I'd suggest that we combine forces (developers interested in working on it / potential donations), as to avoid working on too many different versions. Nylas Mail is a complex application and the more we can unify direction, the likelier we will end-up with a working / bug-free version of Nylas Mail.

Here's the link to his fork: https://github.com/Foundry376/Merani

<img width="786" alt="screen shot 2017-08-07 at 4 44 32 pm" src="https://user-images.githubusercontent.com/2619225/29029292-e3e015a0-7b8f-11e7-9626-7d8f0b7a6d1e.png">

Could we have an open dialog on this? @bengotow

**Comment by step21** [comment]
I think this is already known. However as long as he doesn't have any running code, nor a timeline of when his C++ backend is ready, I do not think it makes sense to wait for him. This is ofc just my personal opinion as a user or potential contributor.

**Comment by franzos** [comment]
@step21 good point! I've reached out to Ben, to figure out what his plans are and whether there's a rough timeline. What worries me the most is, that we'll soon see two or more versions of Nylas Mail, with possibly future incompatibilities (ex. plugins).

One one hand, this is the beauty of open source, on the other hand, it's a curse because we may end up with two versions, that both work partially, and never as well as if there was only one that we all develop, maintain and contribute to together. Looking at the number of issues of the last, original build, there's a lot of work to do.

**Comment by Sidesplitter** [comment]
@step21 Even when the C++ backend is not join yet, when merging, we could potentially help him with the whole rewrite. If we're going to merge, we should probably do it from the start. Doing the same work twice seems rather counterproductive.

**Comment by step21** [comment]
Of course it is often better to contribute/collaborate if possible. But I cannot judge how feasible that is. At least those 2 forks were started independently, with possibly different intentions. it might be very simple to combine the efforts, but it might also be very difficult depending on the people involved, intentions and how they are used to work. The last time f.e. I checked @bengotows fork, it did not seem that there was any c++ stuff committed, probably as he also said nothing is ready to try, so I assumed that he first wanted to get some groundwork done before publishing anything. Certainly good to get in touch as @franzos said and discuss/investigate.

**Comment by bengotow** [comment]
Hey folks! I think consolidating efforts could be a great idea - I've been keeping a bit of a low profile while I work on my fork, but mostly because I'm not ready to provide support for the new C++ core and I'm still moving things around quite a bit. 

I put together a [public roadmap here](https://github.com/Foundry376/Merani/blob/master/ROADMAP.md) that will give you a better idea of what's left to do and where I'm hoping to take the project after the first version is done. It's definitely getting close to the point where folks could merge in improvements made here on `nylas-mail-lives` or tackle projects like localization, improved linux support, etc. and not get trampled by refactoring.

Also—just to be upfront, I'm planning to re-implement and host cloud infrastructure and continue the "Nylas Pro" subscription model under a new brand (probably "Merani").  A lot of open-source projects have trouble retaining contributors long term—folks burn out serving the open source community and users don't often donate enough to make continued development financially worthwhile. HapiJS is a great recent example (https://github.com/hapijs/contrib/issues/110).

Nylas Mail didn't make enough money for Nylas to justify continued investment in it, but I think it has a crazy rare opportunity to be both a successful product and a successful open-source project. To me, success looks like this:

- Merani is a successful open source project that is actively maintained by contributors and users all over the world. People can see how it works, fix bugs, add features, write themes / plugins, etc.

- Merani Pro subscriptions make enough money to cover:
  + Infrastructure for snooze, read receipts, cloud mail rules, etc.
  + High-quality, timely support for paying users. (Not via GitHub!)
  + One or more full-time contributors that can drive the project forward, approve PRs, write documentation, cut and QA releases, fix critical issues, etc.

I'd love to get everyone's thoughts as I work toward a 1.0!

**Comment by chipbuster** [comment]
@bengotow I actually emailed Nylas asking if there was a way to pay to support the client, and was told that the only way to give them money was by paying for access to the dev API (which I don't particularly need).

I'm just a broke-ass grad student, but if you can get that going, I'll happily pay whatever I can afford. The opportunity to have a mail client on Linux that actually has both looks and functionality is just too good to give up.

**Comment by seesemichaelj** [comment]
Don't want to be a debbie-downer, but this is definitely not the communication channel to discuss such things

**Comment by seesemichaelj** [comment]
Just to follow up on this, this is definitely a desire by many of the main contributors. Looking at Merani restructuring, the merge effort would never end until we stopped working on Nylas Mail Lives. Therefore, I suggest that people can merge individual features from NML into Merani on their own accord. If there is a point where we see it fit to leave NML in full support of Merani (which is not yet upon us), we will merge whatever hasn't been merge that we think should be incorporated.

I'm closing this issue for now; feel free to continue discussion.

**Comment by step21** [comment]
To continue this discussion - Merani now seems to be Mailspring (also mentioned in Nylas' blog post ) and its repo is here. https://github.com/Foundry376/Mailspring However, it probably doesn't work yet even from the repo, as the /mail-sync submodule is unavailable (presumably still private).
It is supposed to be published this or next week, maybe it will be published then.

**Comment by seesemichaelj** [comment]
I begun merging core features that we added here at NML into the Mailspring; see https://github.com/Foundry376/Mailspring/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Aseesemichaelj%20. I omitted anything related to documentation, Continuous Integration (Travis/AppVeyor), and things that were not applicable (isomorphic-core, client-sync, changes that did not apply to the altered codebase). I will continue merging core features as PRs to Mailspring as they occur.

**Comment by step21** [comment]
Cool @seesemichaelj - let's see how they handle that. If I may ask, how do you test that code? Personally, I cloned the mailspring repo but it didn't run anything yet. The sync engine fails to download and without the main app just complains about its database being corrupted (not existing).

**Comment by seesemichaelj** [comment]
A good question. I have not tested mailspring yet due to similar issues, so the PRs are untested officially :D
