### ISSUE TITLE
Fix CI for Mac OS

### ISSUE THREAD

**Issue by dweremeichik** [nylas-mail-lives/nylas-mail#8]
Currently CI for Mac OS on Travis is failing due to missing files for the code signing process.
It is also blocking the Linux build process.

- [x] Look into how the code signing process works
- [ ] Remove code signing to get travis ci working again.
- [ ] Figure out if we can create our own files to sign with (instead of using the ones from Nylas)
- [ ] Fix the signing process.

**Comment by GrayW** [comment]
Hey @dweremeichik - CI is something I've been meaning to learn about, so I'm willing to try and help here. Unfortunately, I have no prior experience.

The Slack invitation link has expired, otherwise I would have jumped in and asked in there. Feel free to send an invite if you'd like me to get in the way here :).

**Comment by dweremeichik** [comment]
@GrayW We are working on fixing the slack invites. I can invite you directly, but need an email address to do so. Also, I need to update this issue, we are looking at killing code signing for now, so that we can get the travis builds working. If you are interested in getting it to work with the code signing, that would be a very welcome addition.

**Comment by GrayW** [comment]
@dweremeichik gray@live.co.uk
I'll give it a bash and see what I can break.

**Comment by dweremeichik** [comment]
@GrayW Invited to slack.

**Comment by GrayW** [comment]
Currently learning about the process and working on a test solution with temporary cert files for signing.
Will update this issue as soon as/if I can get the build to pass with SIGN_BUILD=true

**Comment by tsikerdekis** [comment]
Does this commit fix the build issue with travis? ce5f3ba61c5602584dd49795408f3bc70655327a

**Comment by dweremeichik** [comment]
It is an attempt to, yes. For some reason the Mac build fails when trying to install "better-sqlite3". Also, If what I have seen is correct, the Travis builds might be pointless.... I don't think there is anything set up to run the tests. I think Nylas was just using it to build executables.

**Comment by dweremeichik** [comment]
It seems like this travis file: nylas-mail/packages/client-app/.travis.yml should do what we want (I think).

**Comment by tsikerdekis** [comment]
Yes the mac os x generates a missing codesign value. It says we can use --force to ignore the warnings. I am not sure where to place that however in the travis.yml
Building executables is good but then again travis supports as it is os x and linux builds. Can we also build windows on it.

**Comment by dweremeichik** [comment]
You can set an environment variable to disable codesigning in the .travis.yml. `SIGN_BUILD=false`. Windows is done through appVeyor. We need to get an email address for the ORG set up for that.

**Comment by GrayW** [comment]
Thanks @dweremeichik  I'll take a closer look at that one this afternoon when I get home.

**Comment by GrayW** [comment]
Had been working on this as a temporary solution: [grayw / ci-fix / travis](https://github.com/GrayW/nylas-mail/blob/ci-fix/.travis.yml#L34-L43) which looked like it was going to work until it hit one of the tasks I hadn't spotted.
It then kicked up an error about the missing keyPassword, so I'm probably heading in the wrong direction with this temporary fix, should work towards making the current tasks work again rather than finding work-arounds.

Possible new todos:

- [ ] Remove env variables that I created
- [ ] Create new environment variable APPLE_CODESIGN_KEY_PASSWORD with p12 password
- [ ] Update cert names in mac keychain task ( @dweremeichik might need to look in to Apple Developer Team registration if it can't use self signed - still testing )
- [ ] Move certs to client-app/build/resources/certs/mac?? 
```
getCertData = () => {
    const certs = path.resolve(path.join(grunt.config('buildDir'), 'resources', 'certs', 'mac'));
```

**Comment by dweremeichik** [comment]
@GrayW I don't have a Mac, so my help may be a bit slow/limited here. That bit about the cert path seems familiar. Take a look at the before install portion of the travis.yml file.

**Comment by GrayW** [comment]
Travis builds with code signing enabled: <img src="https://travis-ci.org/GrayW/nylas-mail.svg?branch=ci-fix">

Not perfect and still a couple of tweaks needed as mentioned in the slack channel. The most important of which is encrypting the certs. This shouldn't pose much of an issue though. I'll make those changes tomorrow morning.
