### ISSUE TITLE
[win] 2.2.0 install error

### ISSUE THREAD

**Issue by kometchtech** [nylas-mail-lives/nylas-mail#81]
Hello, 

I attempted to install NylasMailSetup-2.2.0.exe with Windows 10 Pro 1703, but an error like image was displayed and it could not be installed.

![nylas_220](https://user-images.githubusercontent.com/5137077/30779340-d28b1034-a128-11e7-81b8-846582da09e5.JPG)

Regards.

**Comment by seesemichaelj** [comment]
Thanks for the heads up, will look into this tomorrow!

**Comment by seesemichaelj** [comment]
I encountered the same error on Windows; the Ubuntu and Mac installers seemed to run fine. Looks like the issue occurs on startup of the application rather than during the install process. Still looking into it

**Comment by seesemichaelj** [comment]
Alright, this was due to a build issue with the Lerna system. If `npm install` fails prematurely, some temporary changes that Lerna makes do not get reverted (i.e. `package.json` is effectively "corrupt") and there were missing modules. There was also a 32 bit vs 64 bit issue.

I have fixed the problem and the release updated. The application is now a 64 bit application. If someone needs 32 bit, we may be able to try again to get it to build under 32 bits but I was having issues.

You can find the binary at https://github.com/nylas-mail-lives/nylas-mail/releases/download/2.2.0/NylasMailSetup-2.2.0-x64.exe

**Comment by kometchtech** [comment]
Thank you to contact us.
Was it a build problem?
I also confirmed that I can install without any problem with binary that was also informative.

Thank you for support.

Regards.

**Comment by seesemichaelj** [comment]
It was a build problem where I forgot to set something, npm install failed and some remnants were not removed after I fixed it causing some modules to not be built in.
